kind: pipeline
type: docker
name: Deploy site

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: Install dependencies
    image: node:18-alpine
    commands:
      - yarn install --immutable

  - name: Build
    image: node:18-alpine
    commands:
      - yarn build

  - name: Deploy to Firebase
    image: node:18-alpine
    environment:
      FIREBASE_TOKEN:
        from_secret: firebase-token
    commands:
      - yarn deploy
